Proyecto_MVC/WebApplication1/Controllers/PrincipalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class PrincipalController : Controller
    {
        // GET: Principal
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Ayuda()
        {
            return View();
        }
        public ActionResult Acerca()
        {
            return View();
        }
        public ActionResult Contacto()
        {
            return View();
        }
    }
}

Proyecto_MVC/WebApplication1/Controllers/TBLClientesController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class TBLClientesController : Controller
    {
        // GET: TBLClientes
        public ActionResult Index()
        {
            Proyecto_MVC_BD db = new Proyecto_MVC_BD(); //Conectar a la bd

            var clientes = db.Clientes; //Traer la tabla empleados

            return View(clientes.ToList()); //Enviar la lista de empleados a la vista
        }

        public ActionResult Nuevo() //Se usa action result para devolver una vista
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(FormCollection collection) //Se usa action result para devolver una vista
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Proyecto_MVC_BD db = new Proyecto_MVC_BD(); //Conectar a la bd
                    Clientes cliente = new Clientes(); //Crear un objeto del modelo empleados
                    cliente.Nombre = collection["Nombre"];
                    cliente.Documento = collection["Documento"];
                    cliente.Telefono = collection["Telefono"];
                    cliente.Email = collection["Email"];
                    cliente.Direccion = collection["Direccion"];

                    db.Clientes.Add(cliente); //Agregar el objeto a la tabla empleados
                    db.SaveChanges(); //Guardar los cambios en la bd

                    return RedirectToAction("Index"); //Redireccionar a la vista index
                }

                return View(collection);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Editar(int id)
        {
            Proyecto_MVC_BD db = new Proyecto_MVC_BD(); //Conectar a la bd
            var cliente = db.Clientes.Find(id); //Buscar el empleado por id
            return View(cliente); //Enviar el objeto empleado a la vista
        }
        [HttpPost]
        public ActionResult Editar(Clientes model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Proyecto_MVC_BD db = new Proyecto_MVC_BD(); // conectar a la bd
                    var clientemodificado = db.Clientes.Find(model.ClienteID); //Buscar el cliente en la bd por id
                    clientemodificado.Nombre = model.Nombre;
                    clientemodificado.Documento = model.Documento;
                    clientemodificado.Telefono = model.Telefono;
                    clientemodificado.Email = model.Email;
                    clientemodificado.Direccion = model.Direccion;

                    db.Entry(clientemodificado).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
                
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            } 
        }
        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            try
            {
                using (Proyecto_MVC_BD db = new Proyecto_MVC_BD())
                {
                    var cliente = db.Clientes.Find(id); //Buscar el cliente por id
                    db.Clientes.Remove(cliente); //Eliminar el cliente
                    db.SaveChanges(); //Guardar los cambios en la bd
                }
                return RedirectToAction("Index"); //Redirigir al index
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

Proyecto_MVC/WebApplication1/Controllers/TBLEmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.ModelBinding;
using System.Web.Mvc;
using System.Web.Services.Description;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class TBLEmpleadoController : Controller
    {
        // GET: TBLEmpleado
        public ActionResult Index()
        {
            Proyecto_MVC_BD db = new Proyecto_MVC_BD(); // Instanciar el contexto de la bd
            var empleados = db.Empleados.ToList(); //Obtener todos los empleados de la tabla empleados
            return View(empleados.ToList()); //Mostrar al index la lista de empleados
        }
        public ActionResult Nuevo() //Se usa action result para devolver una vista
        {
            return View();
        }
        [HttpPost] //indica que este metodo responde a una peticion de la web vía post
        public ActionResult Nuevo(FormCollection collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Proyecto_MVC_BD db = new Proyecto_MVC_BD(); //Conectar a la bd
                    var empleado = new Empleados(); //Crear un objeto de tipo empleado
                    empleado.Nombre = collection["Nombre"]; //Asignar valores al objeto empleado
                    empleado.Documento = collection["Documento"];
                    empleado.Email = collection["Email"];
                    empleado.FechaIngreso = Convert.ToDateTime(collection["FechaIngreso"]);

                    db.Empleados.Add(empleado); //Agregar el objeto a la tabla empleados
                    db.SaveChanges(); //Guardar los cambios en la bd

                    return RedirectToAction("Index"); //Redirigir al index
                }
                return View(collection);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Editar(int id)
        {
            Proyecto_MVC_BD db = new Proyecto_MVC_BD(); //conectar a la bd
            var empleado = db.Empleados.Find(id); //Buscar el empleado por id

            return View(empleado);
        }

        [HttpPost]
        public ActionResult Editar(Empleados model) //Recibir el modelo de empleado modificado de la vista
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (Proyecto_MVC_BD db = new Proyecto_MVC_BD())
                    {
                        var empleadomodi = db.Empleados.Find(model.EmpleadoID); //Buscar el empleado por id
                        //Actualizar los valores del empleado
                        empleadomodi.Nombre = model.Nombre;
                        empleadomodi.Documento = model.Documento;
                        empleadomodi.Email = model.Email;
                        empleadomodi.FechaIngreso = model.FechaIngreso;

                        db.Entry(empleadomodi).State = System.Data.Entity.EntityState.Modified; //Marcar el objeto como modificado
                        db.SaveChanges(); //Guardar los cambios en la bd
                    }
                    return RedirectToAction("Index"); //Redirigir al index
                }
                return View(model); //Si el modelo no es valido, regresar la vista con el modelo
            }

            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            try
            {
                using (Proyecto_MVC_BD db = new Proyecto_MVC_BD())
                {
                    var empleado = db.Empleados.Find(id); //Buscar el empleado por id
                    db.Empleados.Remove(empleado); //Eliminar el empleado
                    db.SaveChanges(); //Guardar los cambios en la bd
                }
                return RedirectToAction("Index"); //Redirigir al index
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

Proyecto_MVC/WebApplication1/Controllers/TBLProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class TBLProductosController : Controller
    {
        // GET: TBLProductos
        public ActionResult Index()
        {
            Proyecto_MVC_BD db = new Proyecto_MVC_BD(); //Instanciar el contexto de la db
            var productos = db.Productos.ToList(); //Obtener la lista de productos desde la db
            return View(productos.ToList()); //Mandar la lista de productos a la vista
        }

        public ActionResult Nuevo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Nuevo(FormCollection collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Proyecto_MVC_BD db = new Proyecto_MVC_BD();
                    Productos producto = new Productos();
                    producto.NombreProducto = collection["NombreProducto"];
                    producto.Descripcion = collection["Descripcion"];
                    producto.Precio = Convert.ToDecimal(collection["Precio"]);
                    producto.Stock = Convert.ToInt32(collection["Stock"]);
                    
                    db.Productos.Add(producto);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Editar (int id)
        {
            Proyecto_MVC_BD db = new Proyecto_MVC_BD();
            var producto = db.Productos.Find(id); //buscar el producto por id
            return View(producto);
        }
        [HttpPost]
        public ActionResult Editar(Productos model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Proyecto_MVC_BD db = new Proyecto_MVC_BD();
                    var producto = db.Productos.Find(model.IdProducto);
                    producto.NombreProducto = model.NombreProducto;
                    producto.Descripcion = model.Descripcion;
                    producto.Precio = Convert.ToDecimal(model.Precio);
                    producto.Stock = Convert.ToInt32(model.Stock);

                    db.Entry(producto).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            try
            {
                using (Proyecto_MVC_BD db = new Proyecto_MVC_BD())
                {
                    var producto = db.Productos.Find(id);
                    db.Productos.Remove(producto);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                throw new Exception (ex.Message);
            }
        }
    }
}

Proyecto_MVC/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Proyecto_MVC</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 565px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #345863;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @@media screen and (max-width: 767px) { /*@@ evita que se ponga como codigo de c#*/
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Facturación</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        @Html.ActionLink("Inicio", "Index", "Principal")
                    </li>
                    <li>
                        @Html.ActionLink("Acerca de", "Acerca", "Principal")
                    </li>
                    <li>
                        @Html.ActionLink("Ayuda", "Ayuda", "Principal")
                    </li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid text-center">
        <div class="row content">
            <div class="col-sm-2 sidenav">

                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" href="#collapse1">Empleados</a>
                            </h4>
                        </div>
                        <div id="collapse1" class="panel-collapse collapse">
                            <div class="panel-body">@Html.ActionLink("Empleado","Index", "TBLEmpleado")</div>
                        </div>
                    </div>
                </div>


                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" href="#collapse2">Clientes</a>
                            </h4>
                        </div>
                        <div id="collapse2" class="panel-collapse collapse">
                            <div class="panel-body">@Html.ActionLink("Cliente","Index","TBLClientes")</div>
                        </div>
                    </div>
                </div>

                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" href="#collapse3">Productos</a>
                            </h4>
                        </div>
                        <div id="collapse3" class="panel-collapse collapse">
                            <div class="panel-body">@Html.ActionLink("Producto","Index","TBLProductos")</div>
                        </div>
                    </div>
                </div>



            </div>
            <div class="col-sm-10 text-left">
                @RenderBody()


            </div>
        </div>
    </div>

    <footer class="container-fluid text-center">
        <p>Footer Text</p>
    </footer>

</body>
</html>